package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate JP;
    private DbIterator CH1;
    private DbIterator CH2;
    private DbIterator[] CHILDREN;
    private ArrayList<Tuple> TARRAY;
    private Iterator<Tuple> IT;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        JP = p;
        CH1 = child1;
        CH2 = child2;
        CHILDREN = new DbIterator[] {CH1, CH2};
        TARRAY = new ArrayList<Tuple>();
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return JP;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return CH1.getTupleDesc().getFieldName(JP.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return CH2.getTupleDesc().getFieldName(JP.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(CH1.getTupleDesc(), CH2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        CH1.open();
        CH2.open();
        // int count = 0;
        while (CH1.hasNext()) {
            Tuple t1 = CH1.next();
            while (CH2.hasNext()) {
                Tuple t2 = CH2.next();
                // count++;
                if (JP.filter(t1, t2)) {
                    Tuple t3 = new Tuple(this.getTupleDesc());
                    int i = 0;
                    for (; i < t1.getTupleDesc().numFields(); i++)
                        t3.setField(i, t1.getField(i));
                    for (; i < t3.getTupleDesc().numFields(); i++)
                        t3.setField(i, t2.getField(i - t1.getTupleDesc().numFields()));
                    // System.out.println(t3.toString());
                    TARRAY.add(t3); // create a array of the resulting tuples
                }
            }
            CH2.rewind();
        }

        // System.out.println("countjoin is "+count);
        IT = TARRAY.iterator();
        super.open();
    }

    public void close() {
        // some code goes here
        super.close();
        CH1.close();
        CH2.close();
        IT = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        IT = TARRAY.iterator();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if (IT.hasNext())
            return IT.next();
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return CHILDREN;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        CHILDREN = children;
        CH1 = CHILDREN[0];
        CH2 = CHILDREN[1];
    }

    public void print() {
        for (int i = 0; i < TARRAY.size(); i++)
            System.out.println(TARRAY.get(i).toString());
    }

}
